{"infourl": "https://www.adafruit.com/distributors", "entity": "Nerokas Engineering", "entitytype": "Distributor", "text": "Nerokas Engineering", "attributeinfo": {"major_region": "Africa", "country": "Kenya", "url": "http://store.nerokas.co.ke/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ECOROBOTICS", "entitytype": "Distributor", "text": "ECOROBOTICS", "attributeinfo": {"major_region": "Africa", "country": "Namibia", "url": "https://www.ecorobotics.com.na/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Center4Tech", "entitytype": "Distributor", "text": "Center4Tech", "attributeinfo": {"major_region": "Africa", "country": "Nigeria", "url": "http://www.center4tech.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Communica", "entitytype": "Distributor", "text": "Communica", "attributeinfo": {"major_region": "Africa", "country": "South_Africa", "url": "http://www.communica.co.za/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Micro Robotics", "entitytype": "Distributor", "text": "Micro Robotics", "attributeinfo": {"major_region": "Africa", "country": "South_Africa", "url": "http://www.robotics.org.za"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "iMake Education Ltd.", "entitytype": "Distributor", "text": "iMake Education Ltd.", "attributeinfo": {"major_region": "Asia", "country": "China", "url": "https://imakeedu.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "PCBWay", "entitytype": "Distributor", "text": "PCBWay", "attributeinfo": {"major_region": "Asia", "country": "China", "url": "https://www.pcbway.com/project/gifts.html"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "TinySine", "entitytype": "Distributor", "text": "TinySine", "attributeinfo": {"major_region": "Asia", "country": "China", "url": "http://www.tinysine.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Fatbars Limited", "entitytype": "Distributor", "text": "Fatbars Limited", "attributeinfo": {"major_region": "Asia", "country": "Hong_Kong", "url": "http://www.feedyourbrains.info/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Welfare Electronic Component Ltd", "entitytype": "Distributor", "text": "Welfare Electronic Component Ltd", "attributeinfo": {"major_region": "Asia", "country": "Hong_Kong", "url": "http://wecl-stem.com/product-category/brands/adafruit/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Adhira Technologies", "entitytype": "Distributor", "text": "Adhira Technologies", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.adhiratech.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Crazy Pi", "entitytype": "Distributor", "text": "Crazy Pi", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.crazypi.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Engineerstoys - Raceway Impex", "entitytype": "Distributor", "text": "Engineerstoys - Raceway Impex", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.engineerstoys.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Fab.to.Lab", "entitytype": "Distributor", "text": "Fab.to.Lab", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "https://www.fabtolab.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "iodParts Technologies Private Limited", "entitytype": "Distributor", "text": "iodParts Technologies Private Limited", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "https://goo.gl/maps/KREvq4mTP6T2"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MG Super Labs", "entitytype": "Distributor", "text": "MG Super Labs", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.mgsuperlabs.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ProtoCentral", "entitytype": "Distributor", "text": "ProtoCentral", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.protocentral.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ROBU.IN", "entitytype": "Distributor", "text": "ROBU.IN", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "https://robu.in/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Silverline Electronics", "entitytype": "Distributor", "text": "Silverline Electronics", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "https://www.silverlineelectronics.in/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tanna TechBiz LLP", "entitytype": "Distributor", "text": "Tanna TechBiz LLP", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.tannatechbiz.com/home.html"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tenet Techtronics", "entitytype": "Distributor", "text": "Tenet Techtronics", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "http://www.tenettech.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Thingbits Electronics", "entitytype": "Distributor", "text": "Thingbits Electronics", "attributeinfo": {"major_region": "Asia", "country": "India", "url": "https://www.thingbits.net/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electronic.Can", "entitytype": "Distributor", "text": "Electronic.Can", "attributeinfo": {"major_region": "Asia", "country": "Israel", "url": "https://hackstore.co.il/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Akizuki Denshi Tsusho Co.", "entitytype": "Distributor", "text": "Akizuki Denshi Tsusho Co.", "attributeinfo": {"major_region": "Asia", "country": "Japan", "url": "http://akizukidenshi.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Gizmo Music", "entitytype": "Distributor", "text": "Gizmo Music", "attributeinfo": {"major_region": "Asia", "country": "Japan", "url": "http://www.gizmo-music.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Sengoku Densyo Co., Ltd.", "entitytype": "Distributor", "text": "Sengoku Densyo Co., Ltd.", "attributeinfo": {"major_region": "Asia", "country": "Japan", "url": "http://www.sengoku.co.jp/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Switch Science", "entitytype": "Distributor", "text": "Switch Science", "attributeinfo": {"major_region": "Asia", "country": "Japan", "url": "http://www.switch-science.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "elektrojo", "entitytype": "Distributor", "text": "elektrojo", "attributeinfo": {"major_region": "Asia", "country": "Jordan", "url": "http://elektrojo.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Plusivo Jordan", "entitytype": "Distributor", "text": "Plusivo Jordan", "attributeinfo": {"major_region": "Asia", "country": "Jordan", "url": " https://www.plusivo.jo"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "EVA Electronics Co.", "entitytype": "Distributor", "text": "EVA Electronics Co.", "attributeinfo": {"major_region": "Asia", "country": "Kuwait", "url": "https://www.evakw.com/en/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Idea Link ", "entitytype": "Distributor", "text": "Idea Link ", "attributeinfo": {"major_region": "Asia", "country": "Kuwait", "url": "https://idealink.net/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Autobotic Solution", "entitytype": "Distributor", "text": "Autobotic Solution", "attributeinfo": {"major_region": "Asia", "country": "Malaysia", "url": "http://www.autobotic.com.my/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Cytron Technologies Sdn Bhd", "entitytype": "Distributor", "text": "Cytron Technologies Sdn Bhd", "attributeinfo": {"major_region": "Asia", "country": "Malaysia", "url": "http://www.cytron.com.my/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Micro Tesseract Enterprise", "entitytype": "Distributor", "text": "Micro Tesseract Enterprise", "attributeinfo": {"major_region": "Asia", "country": "Malaysia", "url": "http://store.microtesseract.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Petra International LLC", "entitytype": "Distributor", "text": "Petra International LLC", "attributeinfo": {"major_region": "Asia", "country": "Oman", "url": "http://www.petra-electronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Rastek", "entitytype": "Distributor", "text": "Rastek", "attributeinfo": {"major_region": "Asia", "country": "Pakistan", "url": "http://www.rastek.pk/index.php?"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Circuit-Help Partners Co.", "entitytype": "Distributor", "text": "Circuit-Help Partners Co.", "attributeinfo": {"major_region": "Asia", "country": "Philippines", "url": "http://www.circuit-help.com.ph/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Circuitrocks", "entitytype": "Distributor", "text": "Circuitrocks", "attributeinfo": {"major_region": "Asia", "country": "Philippines", "url": "http://circuit.rocks/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "CREATELABZ", "entitytype": "Distributor", "text": "CREATELABZ", "attributeinfo": {"major_region": "Asia", "country": "Philippines", "url": "https://store.createlabz.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Makerlab Electronics", "entitytype": "Distributor", "text": "Makerlab Electronics", "attributeinfo": {"major_region": "Asia", "country": "Philippines", "url": "http://www.makerlab-electronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Geeks Valley", "entitytype": "Distributor", "text": "Geeks Valley", "attributeinfo": {"major_region": "Asia", "country": "Saudi_Arabia", "url": "http://geeksvalley.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "12Geeks", "entitytype": "Distributor", "text": "12Geeks", "attributeinfo": {"major_region": "Asia", "country": "Singapore", "url": "http://12geeks.com/shop/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ACP Computer Training school Pte Ltd", "entitytype": "Distributor", "text": "ACP Computer Training school Pte Ltd", "attributeinfo": {"major_region": "Asia", "country": "Singapore", "url": "https://www.kidscode.sg/hardware-kit/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Amicus Engineering Pte. Ltd.", "entitytype": "Distributor", "text": "Amicus Engineering Pte. Ltd.", "attributeinfo": {"major_region": "Asia", "country": "Singapore", "url": "http://amicus.com.sg"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MakerSupplies Singapore", "entitytype": "Distributor", "text": "MakerSupplies Singapore", "attributeinfo": {"major_region": "Asia", "country": "Singapore", "url": "https://www.makersupplies.sg"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ROBOT R US", "entitytype": "Distributor", "text": "ROBOT R US", "attributeinfo": {"major_region": "Asia", "country": "Singapore", "url": "http://www.robot-r-us.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Singapore Robotic", "entitytype": "Distributor", "text": "Singapore Robotic", "attributeinfo": {"major_region": "Asia", "country": "Singapore", "url": "http://www.sgbotic.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ArtRobot", "entitytype": "Distributor", "text": "ArtRobot", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://artrobot.co.kr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ICbanQ", "entitytype": "Distributor", "text": "ICbanQ", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://www.icbanq.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "JK EMC", "entitytype": "Distributor", "text": "JK EMC", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://www.toolparts.co.kr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MechaSolution", "entitytype": "Distributor", "text": "MechaSolution", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://www.mechasolution.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "NTREX, Inc.- Devicemart", "entitytype": "Distributor", "text": "NTREX, Inc.- Devicemart", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://www.devicemart.co.kr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "OPENALL CO.,LTD", "entitytype": "Distributor", "text": "OPENALL CO.,LTD", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "https://www.openidea.co.kr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robotscience", "entitytype": "Distributor", "text": "Robotscience", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://www.robotscience.co.kr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "VCTEC KOREA", "entitytype": "Distributor", "text": "VCTEC KOREA", "attributeinfo": {"major_region": "Asia", "country": "South_Korea", "url": "http://www.vctec.co.kr"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Deryuantech", "entitytype": "Distributor", "text": "Deryuantech", "attributeinfo": {"major_region": "Asia", "country": "Taiwan", "url": "http://www.oceansky-technology.com/commerce/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "INIKI Electronics Co., LTD", "entitytype": "Distributor", "text": "INIKI Electronics Co., LTD", "attributeinfo": {"major_region": "Asia", "country": "Taiwan", "url": "http://www.icshop.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Quark Info. Corp.", "entitytype": "Distributor", "text": "Quark Info. Corp.", "attributeinfo": {"major_region": "Asia", "country": "Taiwan", "url": "http://www.sandal.tw/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Arduitronics", "entitytype": "Distributor", "text": "Arduitronics", "attributeinfo": {"major_region": "Asia", "country": "Thailand", "url": "http://www.arduitronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ThaiEasyElec", "entitytype": "Distributor", "text": "ThaiEasyElec", "attributeinfo": {"major_region": "Asia", "country": "Thailand", "url": "http://www.ThaiEasyElec.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "www.direnc.net", "entitytype": "Distributor", "text": "www.direnc.net", "attributeinfo": {"major_region": "Asia", "country": "Turkey", "url": "http://www.direnc.net/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Besomi Electronics LLC", "entitytype": "Distributor", "text": "Besomi Electronics LLC", "attributeinfo": {"major_region": "Asia", "country": "United_Arab_Emirates", "url": "https://besomi.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Edwin Robotics", "entitytype": "Distributor", "text": "Edwin Robotics", "attributeinfo": {"major_region": "Asia", "country": "United_Arab_Emirates", "url": "https://shop.edwinrobotics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Next Power Electronics", "entitytype": "Distributor", "text": "Next Power Electronics", "attributeinfo": {"major_region": "Asia", "country": "United_Arab_Emirates", "url": "http://www.oncomponents.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Zero Ohm", "entitytype": "Distributor", "text": "Zero Ohm", "attributeinfo": {"major_region": "Asia", "country": "United_Arab_Emirates", "url": "http://www.zeroohm.ae/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Xuan Vinh Tech", "entitytype": "Distributor", "text": "Xuan Vinh Tech", "attributeinfo": {"major_region": "Asia", "country": "Viet_Nam", "url": "https://xuanvinhtech.com/en/index.html"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Aus3D", "entitytype": "Distributor", "text": "Aus3D", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "http://www.aus3d.com.au/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Core Electronics", "entitytype": "Distributor", "text": "Core Electronics", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "http://www.core-electronics.com.au/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Little Bird Electronics", "entitytype": "Distributor", "text": "Little Bird Electronics", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "http://littlebirdelectronics.com.au/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pakronics", "entitytype": "Distributor", "text": "Pakronics", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "http://www.pakronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Phipps Electronics", "entitytype": "Distributor", "text": "Phipps Electronics", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "https://www.phippselectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Small Devices", "entitytype": "Distributor", "text": "Small Devices", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "https://smalldevices.com.au"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "The Brainary", "entitytype": "Distributor", "text": "The Brainary", "attributeinfo": {"major_region": "South_Pacific", "country": "Australia", "url": "https://www.thebrainary.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Learning Developments", "entitytype": "Distributor", "text": "Learning Developments", "attributeinfo": {"major_region": "South_Pacific", "country": "New_Zealand", "url": "https://learningdevelopments.co.nz/collections/adafruit"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Physical Computing AUSTRIA", "entitytype": "Distributor", "text": "Physical Computing AUSTRIA", "attributeinfo": {"major_region": "Europe", "country": "Austria", "url": "http://physicalcomputing.at/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Semaf Electronics", "entitytype": "Distributor", "text": "Semaf Electronics", "attributeinfo": {"major_region": "Europe", "country": "Austria", "url": "http://electronics.semaf.at/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electroshop", "entitytype": "Distributor", "text": "Electroshop", "attributeinfo": {"major_region": "Europe", "country": "Belgium", "url": "http://www.electroshopxl.be/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "FabLab Factory", "entitytype": "Distributor", "text": "FabLab Factory", "attributeinfo": {"major_region": "Europe", "country": "Belgium", "url": "http://www.fablabfactory.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Gotron BVBA", "entitytype": "Distributor", "text": "Gotron BVBA", "attributeinfo": {"major_region": "Europe", "country": "Belgium", "url": "http://www.gotron.be"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MicroControleur Hobby", "entitytype": "Distributor", "text": "MicroControleur Hobby", "attributeinfo": {"major_region": "Europe", "country": "Belgium", "url": "http://shop.mchobby.be/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Erelement", "entitytype": "Distributor", "text": "Erelement", "attributeinfo": {"major_region": "Europe", "country": "Bulgaria", "url": "http://erelement.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robotev", "entitytype": "Distributor", "text": "Robotev", "attributeinfo": {"major_region": "Europe", "country": "Bulgaria", "url": "http://www.robotev.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Mikrotron", "entitytype": "Distributor", "text": "Mikrotron", "attributeinfo": {"major_region": "Europe", "country": "Croatia", "url": "http://www.diykits.eu/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": " RPishop.cz", "entitytype": "Distributor", "text": " RPishop.cz", "attributeinfo": {"major_region": "Europe", "country": "Czech_Republic", "url": "http://rpishop.cz/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robotnik.cz", "entitytype": "Distributor", "text": "Robotnik.cz", "attributeinfo": {"major_region": "Europe", "country": "Czech_Republic", "url": "http://robotnik.cz"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Snail Instruments", "entitytype": "Distributor", "text": "Snail Instruments", "attributeinfo": {"major_region": "Europe", "country": "Czech_Republic", "url": "http://www.snailshop.cz"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "EL-SUPPLY", "entitytype": "Distributor", "text": "EL-SUPPLY", "attributeinfo": {"major_region": "Europe", "country": "Denmark", "url": "http://www.el-supply.dk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Elextra", "entitytype": "Distributor", "text": "Elextra", "attributeinfo": {"major_region": "Europe", "country": "Denmark", "url": "https://www.elextra.dk"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Hippomini", "entitytype": "Distributor", "text": "Hippomini", "attributeinfo": {"major_region": "Europe", "country": "Denmark", "url": " www.hippomini.dk"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Let Elektronik", "entitytype": "Distributor", "text": "Let Elektronik", "attributeinfo": {"major_region": "Europe", "country": "Denmark", "url": "http://www.let-elektronik.dk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MiniElektro", "entitytype": "Distributor", "text": "MiniElektro", "attributeinfo": {"major_region": "Europe", "country": "Denmark", "url": "http://minielektro.dk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "OOMIPOOD", "entitytype": "Distributor", "text": "OOMIPOOD", "attributeinfo": {"major_region": "Europe", "country": "Estonia", "url": "http://www.oomipood.ee"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "YeInternational AS", "entitytype": "Distributor", "text": "YeInternational AS", "attributeinfo": {"major_region": "Europe", "country": "Estonia", "url": "http://www.yeint.ee/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Mandu", "entitytype": "Distributor", "text": "Mandu", "attributeinfo": {"major_region": "Europe", "country": "Finland", "url": "https://www.mandu.fi/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robomaa", "entitytype": "Distributor", "text": "Robomaa", "attributeinfo": {"major_region": "Europe", "country": "Finland", "url": "http://www.robomaa.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Step Systems Ltd.", "entitytype": "Distributor", "text": "Step Systems Ltd.", "attributeinfo": {"major_region": "Europe", "country": "Finland", "url": "http://www.stepsystems.fi"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Triopak Oy", "entitytype": "Distributor", "text": "Triopak Oy", "attributeinfo": {"major_region": "Europe", "country": "Finland", "url": "https://www.triopak.fi/fi"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Generation Robots", "entitytype": "Distributor", "text": "Generation Robots", "attributeinfo": {"major_region": "Europe", "country": "France", "url": "https://www.generationrobots.com/en/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Go Tronic", "entitytype": "Distributor", "text": "Go Tronic", "attributeinfo": {"major_region": "Europe", "country": "France", "url": "http://www.gotronic.fr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Letmeknow", "entitytype": "Distributor", "text": "Letmeknow", "attributeinfo": {"major_region": "Europe", "country": "France", "url": "https://letmeknow.fr/fr/133-adafruit-feather"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Lextronic", "entitytype": "Distributor", "text": "Lextronic", "attributeinfo": {"major_region": "Europe", "country": "France", "url": "http://www.lextronic.fr/R3133-adafruit-industries.html"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "SEMAGEEK", "entitytype": "Distributor", "text": "SEMAGEEK", "attributeinfo": {"major_region": "Europe", "country": "France", "url": "http://boutique.semageek.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "BerryBase", "entitytype": "Distributor", "text": "BerryBase", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://www.berrybase.de/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Buy Zero ", "entitytype": "Distributor", "text": "Buy Zero ", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://buyzero.de/collections/adafruit-produkte"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Eckstein Komponente", "entitytype": "Distributor", "text": "Eckstein Komponente", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://eckstein-shop.de/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "EXP-Tech", "entitytype": "Distributor", "text": "EXP-Tech", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "http://www.exp-tech.de/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MAKERSHOP.DE", "entitytype": "Distributor", "text": "MAKERSHOP.DE", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://www.makershop.de"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Omega Electronic gmbh", "entitytype": "Distributor", "text": "Omega Electronic gmbh", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "http://www.omega-electronic.de/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Paradisetronic.com", "entitytype": "Distributor", "text": "Paradisetronic.com", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://paradisetronic.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pimoroni Germany", "entitytype": "Distributor", "text": "Pimoroni Germany", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://shop.pimoroni.de"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "SHA 256 Systems", "entitytype": "Distributor", "text": "SHA 256 Systems", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "https://sha256systems.eu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Watterott Electronic", "entitytype": "Distributor", "text": "Watterott Electronic", "attributeinfo": {"major_region": "Europe", "country": "Germany", "url": "http://watterott.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "GRobotronics", "entitytype": "Distributor", "text": "GRobotronics", "attributeinfo": {"major_region": "Europe", "country": "Greece", "url": "http://grobotronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Hellas Digital", "entitytype": "Distributor", "text": "Hellas Digital", "attributeinfo": {"major_region": "Europe", "country": "Greece", "url": "http://www.hellasdigital.gr"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "nettop", "entitytype": "Distributor", "text": "nettop", "attributeinfo": {"major_region": "Europe", "country": "Greece", "url": "http://www.nettop.gr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "HQ Elektronika Kft.", "entitytype": "Distributor", "text": "HQ Elektronika Kft.", "attributeinfo": {"major_region": "Europe", "country": "Hungary", "url": "https://hqelektronika.hu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "M\u00e1lna PC Magyarorsz\u00e1g", "entitytype": "Distributor", "text": "M\u00e1lna PC Magyarorsz\u00e1g", "attributeinfo": {"major_region": "Europe", "country": "Hungary", "url": "http://malnapc.hu/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pi-Shop (Hungary)", "entitytype": "Distributor", "text": "Pi-Shop (Hungary)", "attributeinfo": {"major_region": "Europe", "country": "Hungary", "url": "https://www.pi-shop.hu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "RPi Bolt", "entitytype": "Distributor", "text": "RPi Bolt", "attributeinfo": {"major_region": "Europe", "country": "Hungary", "url": "http://www.rpibolt.hu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Media ehf", "entitytype": "Distributor", "text": "Media ehf", "attributeinfo": {"major_region": "Europe", "country": "Iceland", "url": "http://media.is"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Arduino", "entitytype": "Distributor", "text": "Arduino", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "https://www.arduino.cc/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "EFFEGI SRL", "entitytype": "Distributor", "text": "EFFEGI SRL", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "http://www.robotics-3d.com/component/virtuemart/adafruit"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Melopero", "entitytype": "Distributor", "text": "Melopero", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "http://www.melopero.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "PiLover", "entitytype": "Distributor", "text": "PiLover", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "https://www.pilover.com/it/marchio/adafruit/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ROBOT DOMESTICI", "entitytype": "Distributor", "text": "ROBOT DOMESTICI", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "http://www.robot-domestici.it/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robot Italy", "entitytype": "Distributor", "text": "Robot Italy", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "http://www.robot-italy.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "RobotStore", "entitytype": "Distributor", "text": "RobotStore", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "http://www.robotstore.it/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Sogloo", "entitytype": "Distributor", "text": "Sogloo", "attributeinfo": {"major_region": "Europe", "country": "Italy", "url": "http://www.sogloo.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electronic-Shop Sarl", "entitytype": "Distributor", "text": "Electronic-Shop Sarl", "attributeinfo": {"major_region": "Europe", "country": "Luxembourg", "url": "https://www.electronic-shop.lu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Antratek Electronics", "entitytype": "Distributor", "text": "Antratek Electronics", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "https://www.antratek.nl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Bits & Parts", "entitytype": "Distributor", "text": "Bits & Parts", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "http://www.bitsandparts.eu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Floris.cc", "entitytype": "Distributor", "text": "Floris.cc", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "http://www.floris.cc"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "HobbyElectronica", "entitytype": "Distributor", "text": "HobbyElectronica", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "http://www.hobbyelectronica.nl/product-tag/adafruit/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "iPrototype", "entitytype": "Distributor", "text": "iPrototype", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "https://iprototype.nl"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Kiwi Electronics", "entitytype": "Distributor", "text": "Kiwi Electronics", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "http://www.kiwi-electronics.nl"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Opencircuit", "entitytype": "Distributor", "text": "Opencircuit", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "https://opencircuit.shop/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "S.O.S Solutions", "entitytype": "Distributor", "text": "S.O.S Solutions", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "http://www.sossolutions.nl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "van alles en meer", "entitytype": "Distributor", "text": "van alles en meer", "attributeinfo": {"major_region": "Europe", "country": "Netherlands", "url": "http://www.vanallesenmeer.nl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Digital Impuls AS", "entitytype": "Distributor", "text": "Digital Impuls AS", "attributeinfo": {"major_region": "Europe", "country": "Norway", "url": "http://www.digitalimpuls.no/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "BOTLAND B. DERKACZ SP.J.", "entitytype": "Distributor", "text": "BOTLAND B. DERKACZ SP.J.", "attributeinfo": {"major_region": "Europe", "country": "Poland", "url": "https://botland.com.pl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Kamami", "entitytype": "Distributor", "text": "Kamami", "attributeinfo": {"major_region": "Europe", "country": "Poland", "url": "https://kamami.pl/2_adafruit"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ElectroFun", "entitytype": "Distributor", "text": "ElectroFun", "attributeinfo": {"major_region": "Europe", "country": "Portugal", "url": "https://www.electrofun.pt/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "LEDs and Chips", "entitytype": "Distributor", "text": "LEDs and Chips", "attributeinfo": {"major_region": "Europe", "country": "Portugal", "url": "http://ledsandchips.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "PTRobotics", "entitytype": "Distributor", "text": "PTRobotics", "attributeinfo": {"major_region": "Europe", "country": "Portugal", "url": "https://www.ptrobotics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Optimus Digital SRL", "entitytype": "Distributor", "text": "Optimus Digital SRL", "attributeinfo": {"major_region": "Europe", "country": "Romania", "url": "https://www.optimusdigital.ro/ro/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robofun", "entitytype": "Distributor", "text": "Robofun", "attributeinfo": {"major_region": "Europe", "country": "Romania", "url": "http://www.robofun.ro/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "RLX COMPONENTS", "entitytype": "Distributor", "text": "RLX COMPONENTS", "attributeinfo": {"major_region": "Europe", "country": "Slovak_Republic", "url": "http://www.rlx.sk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Galago", "entitytype": "Distributor", "text": "Galago", "attributeinfo": {"major_region": "Europe", "country": "Slovenia", "url": "http://www.galagomarket.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "3DSOMA ", "entitytype": "Distributor", "text": "3DSOMA ", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://www.3dsoma.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "BricoGeek", "entitytype": "Distributor", "text": "BricoGeek", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://tienda.bricogeek.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Cetronic", "entitytype": "Distributor", "text": "Cetronic", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://www.cetronic.es/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electan", "entitytype": "Distributor", "text": "Electan", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://www.electan.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electr\u00f3nica Embajadores", "entitytype": "Distributor", "text": "Electr\u00f3nica Embajadores", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "https://www.electronicaembajadores.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electronica Gimeno S.L.", "entitytype": "Distributor", "text": "Electronica Gimeno S.L.", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://electronicagimeno.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "GRN", "entitytype": "Distributor", "text": "GRN", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://botiga.grn.cat/3-raspberry-pi"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Industrial Shields", "entitytype": "Distributor", "text": "Industrial Shields", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "https://www.industrialshields.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Muchos LEDs", "entitytype": "Distributor", "text": "Muchos LEDs", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://www.muchosleds.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tiendatec", "entitytype": "Distributor", "text": "Tiendatec", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "https://www.tiendatec.es"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Ultra-lab ", "entitytype": "Distributor", "text": "Ultra-lab ", "attributeinfo": {"major_region": "Europe", "country": "Spain", "url": "http://ultra-lab.net"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "CodeKid AB", "entitytype": "Distributor", "text": "CodeKid AB", "attributeinfo": {"major_region": "Europe", "country": "Sweden", "url": "https://codekid.se/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electrokit Sweden AB", "entitytype": "Distributor", "text": "Electrokit Sweden AB", "attributeinfo": {"major_region": "Europe", "country": "Sweden", "url": "https://www.electrokit.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "HiTechChain", "entitytype": "Distributor", "text": "HiTechChain", "attributeinfo": {"major_region": "Europe", "country": "Sweden", "url": "https://hitechchain.se/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Kjell & Co Elektronik AB", "entitytype": "Distributor", "text": "Kjell & Co Elektronik AB", "attributeinfo": {"major_region": "Europe", "country": "Sweden", "url": "http://www.kjell.com/butiker"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "LAWICEL AB", "entitytype": "Distributor", "text": "LAWICEL AB", "attributeinfo": {"major_region": "Europe", "country": "Sweden", "url": "http://www.lawicel-shop.se"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "www.m.nu", "entitytype": "Distributor", "text": "www.m.nu", "attributeinfo": {"major_region": "Europe", "country": "Sweden", "url": "http://www.m.nu"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Fablab Sion", "entitytype": "Hackerspace", "text": "Fablab Sion", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://fablab-sion.ch/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Alltron AG", "entitytype": "Distributor", "text": "Alltron AG", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://www.alltron.ch/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Boxtec", "entitytype": "Distributor", "text": "Boxtec", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://shop.boxtec.ch"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Brack Electronics AG", "entitytype": "Distributor", "text": "Brack Electronics AG", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://www.brack.ch"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Distrelec", "entitytype": "Distributor", "text": "Distrelec", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "https://www.distrelec.biz/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "maker-shop", "entitytype": "Distributor", "text": "maker-shop", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://www.maker-shop.ch/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "pi-shop", "entitytype": "Distributor", "text": "pi-shop", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://www.pi-shop.ch/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Play-Zone", "entitytype": "Distributor", "text": "Play-Zone", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "http://www.play-zone.ch"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ZigoBot", "entitytype": "Distributor", "text": "ZigoBot", "attributeinfo": {"major_region": "Europe", "country": "Switzerland", "url": "www.zigobot.ch"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Demsay Elektronik San ve Tic A.S.", "entitytype": "Distributor", "text": "Demsay Elektronik San ve Tic A.S.", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "https://www.demsay.com/tr/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Infotek Elektronik", "entitytype": "Distributor", "text": "Infotek Elektronik", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "https://www.motorobit.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Inopark Engineering Inc", "entitytype": "Distributor", "text": "Inopark Engineering Inc", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "http://www.robitshop.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "robolinkmarket", "entitytype": "Distributor", "text": "robolinkmarket", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "https://www.robolinkmarket.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Robotistan", "entitytype": "Distributor", "text": "Robotistan", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "http://www.robotistan.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Samm Market", "entitytype": "Distributor", "text": "Samm Market", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "https://market.samm.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Seernd Muhendislik AS", "entitytype": "Distributor", "text": "Seernd Muhendislik AS", "attributeinfo": {"major_region": "Europe", "country": "Turkey", "url": "https://www.kompent.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "DiyLab", "entitytype": "Distributor", "text": "DiyLab", "attributeinfo": {"major_region": "Europe", "country": "Ukraine", "url": "http://diylab.com.ua/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "4tronix", "entitytype": "Distributor", "text": "4tronix", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://www.4tronix.co.uk"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Cool Components", "entitytype": "Distributor", "text": "Cool Components", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://coolcomponents.co.uk"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "CYNTECH COMPONENTS", "entitytype": "Distributor", "text": "CYNTECH COMPONENTS", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": " http://shop.cyntech.co.uk"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Dicey Tech", "entitytype": "Distributor", "text": "Dicey Tech", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "https://www.diceytech.co.uk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Digital Means", "entitytype": "Distributor", "text": "Digital Means", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "https://digitalmeans.co.uk/shop/adafruit-products"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Makersify", "entitytype": "Distributor", "text": "Makersify", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://makersify.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ModMyPi", "entitytype": "Distributor", "text": "ModMyPi", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "https://www.modmypi.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "oomlaut", "entitytype": "Distributor", "text": "oomlaut", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://oomlout.co.uk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pimoroni", "entitytype": "Distributor", "text": "Pimoroni", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://shop.pimoroni.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Proto-Pic", "entitytype": "Distributor", "text": "Proto-Pic", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "https://www.proto-pic.co.uk "}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "RS Components", "entitytype": "Distributor", "text": "RS Components", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://uk.rs-online.com/web/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "SK Pang electronics", "entitytype": "Distributor", "text": "SK Pang electronics", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://www.skpang.co.uk/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tandy", "entitytype": "Distributor", "text": "Tandy", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://www.tandyonline.co.uk"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "The Pi Hut", "entitytype": "Distributor", "text": "The Pi Hut", "attributeinfo": {"major_region": "Europe", "country": "United_Kingdom", "url": "http://thepihut.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Kingston Makerspace", "entitytype": "Hackerspace", "text": "Kingston Makerspace", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.kingstonmakerspace.ca"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": " RobotShop", "entitytype": "Distributor", "text": " RobotShop", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "https://www.robotshop.com/ca/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": " Spool3D Canada", "entitytype": "Distributor", "text": " Spool3D Canada", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "https://spool3d.ca"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ABRA Electronics", "entitytype": "Distributor", "text": "ABRA Electronics", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.abra-electronics.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "BC-Robotics", "entitytype": "Distributor", "text": "BC-Robotics", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.bc-robotics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "BuyaPi.ca", "entitytype": "Distributor", "text": "BuyaPi.ca", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.buyapi.ca"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Canada Robotix", "entitytype": "Distributor", "text": "Canada Robotix", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.canadarobotix.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Creatron Inc.", "entitytype": "Distributor", "text": "Creatron Inc.", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "https://www.creatroninc.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electronic Network Inc", "entitytype": "Distributor", "text": "Electronic Network Inc", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.electronicnetwork.com/en"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Elmwood Electronics", "entitytype": "Distributor", "text": "Elmwood Electronics", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://elmwoodelectronics.ca/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Lee's Electronics", "entitytype": "Distributor", "text": "Lee's Electronics", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.leeselectronic.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "R.P. Electronics", "entitytype": "Distributor", "text": "R.P. Electronics", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.rpelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Red Moon Cosplay Solutions", "entitytype": "Distributor", "text": "Red Moon Cosplay Solutions", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "https://www.redmooncosplaysolutions.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Sayal Electronics & Hobbies", "entitytype": "Distributor", "text": "Sayal Electronics & Hobbies", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://sayal.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Solarbotics", "entitytype": "Distributor", "text": "Solarbotics", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "https://solarbotics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "SpikenzieLabs", "entitytype": "Distributor", "text": "SpikenzieLabs", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.spikenzielabs.com/Catalog/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tip Top Electronic Supply", "entitytype": "Distributor", "text": "Tip Top Electronic Supply", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "http://www.tiptopelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "X2 ROBOTICS", "entitytype": "Distributor", "text": "X2 ROBOTICS", "attributeinfo": {"major_region": "North_America", "country": "Canada", "url": "https://www.x2robotics.ca/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "CR Cibernetica", "entitytype": "Distributor", "text": "CR Cibernetica", "attributeinfo": {"major_region": "North_America", "country": "Costa_Rica", "url": "http://crcibernetica.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ROBOTECH", "entitytype": "Distributor", "text": "ROBOTECH", "attributeinfo": {"major_region": "North_America", "country": "Dominican_Republic", "url": "http://www.robotechrd.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "mini 3D Factory", "entitytype": "Distributor", "text": "mini 3D Factory", "attributeinfo": {"major_region": "North_America", "country": "Guatemala", "url": "http://m3df.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": " Electrolabo", "entitytype": "Distributor", "text": " Electrolabo", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "www.electrolabo.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "330ohms", "entitytype": "Distributor", "text": "330ohms", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.330ohms.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "5Hz Electr\u00f3nica", "entitytype": "Distributor", "text": "5Hz Electr\u00f3nica", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.5hz-electronica.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "A-Electronic's", "entitytype": "Distributor", "text": "A-Electronic's", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.a-electronics.com.mx/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "AG Electronica SA de CV", "entitytype": "Distributor", "text": "AG Electronica SA de CV", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://agelectronica.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ColdFire Electronica", "entitytype": "Distributor", "text": "ColdFire Electronica", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "https://coldfire-electronica.mercadoshops.com.mx"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Cosas de Ingenier\u00eda", "entitytype": "Distributor", "text": "Cosas de Ingenier\u00eda", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://cosasdeingenieria.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "GeekFactory", "entitytype": "Distributor", "text": "GeekFactory", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.geekfactory.mx/tienda"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "IM Ingenieria Multidisciplinaria", "entitytype": "Distributor", "text": "IM Ingenieria Multidisciplinaria", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.ingmulti.com/store/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "kinetronica", "entitytype": "Distributor", "text": "kinetronica", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.kinetroni.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MakerMex", "entitytype": "Distributor", "text": "MakerMex", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://makermex.com/page/homepage"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Sketch3D", "entitytype": "Distributor", "text": "Sketch3D", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "https://sketch3d.com.mx/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "TechMake Electronics", "entitytype": "Distributor", "text": "TechMake Electronics", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://www.techmake.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tesla BEM S de RL MI", "entitytype": "Distributor", "text": "Tesla BEM S de RL MI", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "http://teslabem.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "UNIT ELECTRONICS. ", "entitytype": "Distributor", "text": "UNIT ELECTRONICS. ", "attributeinfo": {"major_region": "North_America", "country": "Mexico", "url": "https://uelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Market Tech PR", "entitytype": "Distributor", "text": "Market Tech PR", "attributeinfo": {"major_region": "North_America", "country": "Puerto_Rico", "url": "http://www.makertechpr.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Ace Monster Toys", "entitytype": "Hackerspace", "text": "Ace Monster Toys", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://acemonstertoys.org/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "HackPittsburgh", "entitytype": "Hackerspace", "text": "HackPittsburgh", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.HackPittsburgh.org"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Make.br", "entitytype": "Hackerspace", "text": "Make.br", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://makebr.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Maker Depot", "entitytype": "Hackerspace", "text": "Maker Depot", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.themakerdepot.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "NextGen SmartyPants, LLC", "entitytype": "Hackerspace", "text": "NextGen SmartyPants, LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.nextgensmartypants.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Reforge Charleston ", "entitytype": "Hackerspace", "text": "Reforge Charleston ", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.reforge.io/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Sector67", "entitytype": "Hackerspace", "text": "Sector67", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://sector67.org"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tampa Hackerspace", "entitytype": "Hackerspace", "text": "Tampa Hackerspace", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://tampahackerspace.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "TekVenture", "entitytype": "Hackerspace", "text": "TekVenture", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://tekventure.org/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": " AndyMark", "entitytype": "Distributor", "text": " AndyMark", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.andymark.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "3DMakerWorld, Inc.", "entitytype": "Distributor", "text": "3DMakerWorld, Inc.", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://3dmakerworld.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "42 Electronics", "entitytype": "Distributor", "text": "42 Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://42electronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Ada's Technical Books", "entitytype": "Distributor", "text": "Ada's Technical Books", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.adasbooks.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "All Electronics Corp", "entitytype": "Distributor", "text": "All Electronics Corp", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.allelectronics.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Allied Electronics", "entitytype": "Distributor", "text": "Allied Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.alliedelec.com/adafruit-industries/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Altex Electronics", "entitytype": "Distributor", "text": "Altex Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.altex.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Arrow Electronics", "entitytype": "Distributor", "text": "Arrow Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.arrow.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "AS220 Industries / Modern Device", "entitytype": "Distributor", "text": "AS220 Industries / Modern Device", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://moderndevice.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Atoms Industries, LLC", "entitytype": "Distributor", "text": "Atoms Industries, LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.atomsindustries.com/adafruit"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "CAD Supply House", "entitytype": "Distributor", "text": "CAD Supply House", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.cadsupplyhouse.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Caytan Enterprise", "entitytype": "Distributor", "text": "Caytan Enterprise", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://vilros.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Chens LLC", "entitytype": "Distributor", "text": "Chens LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.pi-store.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Chicago Electronic Distributors", "entitytype": "Distributor", "text": "Chicago Electronic Distributors", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://chicagodist.com/collections/adafruit-products"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Cornfield Electronics, Inc.", "entitytype": "Distributor", "text": "Cornfield Electronics, Inc.", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.CornfieldElectronics.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Digi-Key Electronics", "entitytype": "Distributor", "text": "Digi-Key Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.digikey.com/en/supplier-centers/a/adafruit?WT.z_link_source=Supplier%2520Index"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Educate-me.net", "entitytype": "Distributor", "text": "Educate-me.net", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.educate-me.net"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electronics123.com, Inc.", "entitytype": "Distributor", "text": "Electronics123.com, Inc.", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.electronics123.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Evil Mad Science LLC", "entitytype": "Distributor", "text": "Evil Mad Science LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.evilmadscience.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Existential Technologies, Inc.", "entitytype": "Distributor", "text": "Existential Technologies, Inc.", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.existech.us/  "}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Farnsworth Electronics LLC", "entitytype": "Distributor", "text": "Farnsworth Electronics LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://farnsworthelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "FunKey", "entitytype": "Distributor", "text": "FunKey", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.funkey.net"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Gearbox Labs, Inc", "entitytype": "Distributor", "text": "Gearbox Labs, Inc", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://store.gearboxlabs.org"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Gravitech", "entitytype": "Distributor", "text": "Gravitech", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://store.gravitech.us/index.html"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Jameco", "entitytype": "Distributor", "text": "Jameco", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.jameco.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Jaycon Systems", "entitytype": "Distributor", "text": "Jaycon Systems", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.jayconsystems.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "kjdelectronics", "entitytype": "Distributor", "text": "kjdelectronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://kjdelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "LaHaie's, LLC", "entitytype": "Distributor", "text": "LaHaie's, LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://lahaies.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Left Coast", "entitytype": "Distributor", "text": "Left Coast", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.leftcoast.biz/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "make717", "entitytype": "Distributor", "text": "make717", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://make717.org/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Maker Shed", "entitytype": "Distributor", "text": "Maker Shed", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.makershed.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Makers Things", "entitytype": "Distributor", "text": "Makers Things", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.makersthings.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "MicroCenter", "entitytype": "Distributor", "text": "MicroCenter", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.microcenter.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Mouser Electronics", "entitytype": "Distributor", "text": "Mouser Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.mouser.com/manufacturer/adafruit/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "oddWires", "entitytype": "Distributor", "text": "oddWires", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.oddwires.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "PepperTech Digital", "entitytype": "Distributor", "text": "PepperTech Digital", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.peppertech.io"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pervasive Digital LLC", "entitytype": "Distributor", "text": "Pervasive Digital LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://shop.pervasive.digital"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pilala", "entitytype": "Distributor", "text": "Pilala", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://pilala.vn/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "PiShop.us", "entitytype": "Distributor", "text": "PiShop.us", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.pishop.us"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Pololu ", "entitytype": "Distributor", "text": "Pololu ", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.pololu.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Tanner Electronics", "entitytype": "Distributor", "text": "Tanner Electronics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.tannerelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "TAW Global, LLC", "entitytype": "Distributor", "text": "TAW Global, LLC", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://tawglobal.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "That\u2019s My Robot", "entitytype": "Distributor", "text": "That\u2019s My Robot", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://ThatsMyRobot.org"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Total Creative Inc", "entitytype": "Distributor", "text": "Total Creative Inc", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://totalcreative.net"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Visual Sound Inc.", "entitytype": "Distributor", "text": "Visual Sound Inc.", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "https://www.visualsound.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "WhyMaker ", "entitytype": "Distributor", "text": "WhyMaker ", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.whymaker.co"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "You-do-it Electronics Center", "entitytype": "Distributor", "text": "You-do-it Electronics Center", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.youdoitelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Zagros Robotics", "entitytype": "Distributor", "text": "Zagros Robotics", "attributeinfo": {"major_region": "North_America", "country": "United_States", "url": "http://www.zagrosrobotics.com/shop/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ADICHIP", "entitytype": "Distributor", "text": "ADICHIP", "attributeinfo": {"major_region": "South_America", "country": "Argentina", "url": "http://www.adichip.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electrocomponentes S.A.", "entitytype": "Distributor", "text": "Electrocomponentes S.A.", "attributeinfo": {"major_region": "South_America", "country": "Argentina", "url": "http://tienda.electrocomponentes.com/ofertas.php3"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ELECTRONICA ELEMON S.A.", "entitytype": "Distributor", "text": "ELECTRONICA ELEMON S.A.", "attributeinfo": {"major_region": "South_America", "country": "Argentina", "url": "https://www.elemon.net"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Gizmojo", "entitytype": "Distributor", "text": "Gizmojo", "attributeinfo": {"major_region": "South_America", "country": "Argentina", "url": "https://www.gizmojo.com.ar"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Open Hacks", "entitytype": "Distributor", "text": "Open Hacks", "attributeinfo": {"major_region": "South_America", "country": "Argentina", "url": "http://www.openhacks.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "AFEL", "entitytype": "Distributor", "text": "AFEL", "attributeinfo": {"major_region": "South_America", "country": "Chile", "url": "https://afel.cl/?v=7516fd43adaa"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Crea3D", "entitytype": "Distributor", "text": "Crea3D", "attributeinfo": {"major_region": "South_America", "country": "Chile", "url": "http://crea3d.cl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Ingenier\u00eda MCI Ltda", "entitytype": "Distributor", "text": "Ingenier\u00eda MCI Ltda", "attributeinfo": {"major_region": "South_America", "country": "Chile", "url": "http://www.mcielectronics.cl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "PC Factory", "entitytype": "Distributor", "text": "PC Factory", "attributeinfo": {"major_region": "South_America", "country": "Chile", "url": "https://www.pcfactory.cl/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "BOGOHACK", "entitytype": "Hackerspace", "text": "BOGOHACK", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": "http://www.bogohack.co"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Ardobot R\u00f3botica S.A.S", "entitytype": "Distributor", "text": "Ardobot R\u00f3botica S.A.S", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": " https://www.ardobot.com"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Dynamo electronics SAS", "entitytype": "Distributor", "text": "Dynamo electronics SAS", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": "http://www.dynamoelectronics.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ELECTRONICAI I+D", "entitytype": "Distributor", "text": "ELECTRONICAI I+D", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": "http://www.didacticaselectronicas.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Electronilab", "entitytype": "Distributor", "text": "Electronilab", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": "https://electronilab.co/marca/adafruit"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "SIGMA ELECTRONICA LTDA.", "entitytype": "Distributor", "text": "SIGMA ELECTRONICA LTDA.", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": "http://www.sigmaelectronica.net/adafruit-c-304.html"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "Vistronica", "entitytype": "Distributor", "text": "Vistronica", "attributeinfo": {"major_region": "South_America", "country": "Colombia", "url": "https://www.vistronica.com/"}}
{"infourl": "https://www.adafruit.com/distributors", "entity": "ROBOTEC", "entitytype": "Distributor", "text": "ROBOTEC", "attributeinfo": {"major_region": "South_America", "country": "Uruguay", "url": "http://www.robotec.com.uy/"}}
